### ISSUE TITLE
Tentative Outline

### ISSUE THREAD

**Issue by jphall663** [navdeep-G/interpretable-ml#13]
- Abstract 
- Introduction
- Simulated data 
  - Global analysis
    - Surrogate DT
    - Decision boundary plot
    - Comparison of global var. imp. methods
  - Local analysis: Comparison of local var. imp. methods
- Credit card data
  - Global analysis: Surrogate DT, decision boundary, global shap
  - Local analysis: Local shap
- Conclusion

**Comment by navdeep-G** [comment]
Do we still want PDP/ICE?

**Comment by jphall663** [comment]
yes - DOH :face_palm:

**Comment by navdeep-G** [comment]
Reopening for reference purposes.
